### ISSUE TITLE
Library dependency problem

### ISSUE THREAD

**Issue by steelcorsy** [tripflex/provision-wifi#7]
Hello! First of all I want to thank you for your wonderful work, I have a problem compiling "wifi-setup-web" when I add the dependency of your library.

Am I doing something wrong? I have not changed any file of the example project and when I do not add the dependency of your library compiles perfectly.

Log error:

[console_log.txt](https://github.com/tripflex/provision-wifi/files/2260882/console_log.txt)

**Comment by tripflex** [comment]
Ahh sorry about that, it's the C fn returning a bool when it's configured as a void function, i'll get that fixed right now and push an update

**Comment by tripflex** [comment]
Fixed in 36a162d35ab0c3ed92064e98fdd6f5db89bf12fb
